In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
from datetime import datetime
from datetime import timedelta
# sns.set(style="darkgrid")
import requests
import pprint
import re
pd.options.display.max_columns = 999
%matplotlib inline

In [2]:
df = pd.read_csv('../Car_Crash/Data/data_cleaned.csv')

In [3]:
feature_list = [
 'Interstate',
 'State_Road',
 'Local_Road_Only',
 'Turnpike',
 'Non_Intersection',
 'Intersection',
 'Signalized_Intersection',
 'Stop_Controlled_Intersection',
 'Unsignalized_Intersection',
 'Alcohol_Related',
 'Drinking_Driver',
 'Underage_Drinking_Driver',
 'Unlicensed',
 'Distracted',
 'Cell_Phone',
 'No_Clearance',
 'Running_Red_Light',
 'Running_Stop_Sign',
 'Tailgating',
 'Cross_Median',
 'Curved_Road',
 'Curve_Driver_Error',
 'Limit_65_MPH',
 'Speeding',
 'Speeding_Related',
 'Aggressive_Driving',
 'Fatigue_/_Asleep',
 'Driver_16_Years_Old',
 'Driver_17_Years_Old',
 'Driver_18_Years_Old',
 'Driver_19_Years_Old',
 'Driver_20_Years_Old',
 'Driver_50_-_64_Years_Old',
 'Driver_65_-_74_Years_Old',
 'Driver_75_Plus',
 'NHTSA_Aggressive_Driving',
 'Weekend',
 'population_zs',
 'median_age_zs',
 'college_zs',
 'unemployment_rate_zs',
 'household_mean_income_zs',
 'Crash_Month_1',
 'Crash_Month_2',
 'Crash_Month_3',
 'Crash_Month_4',
 'Crash_Month_5',
 'Crash_Month_6',
 'Crash_Month_7',
 'Crash_Month_8',
 'Crash_Month_9',
 'Crash_Month_10',
 'Crash_Month_11',
 'Crash_Month_12',
 'Hour_of_Day_0.0',
 'Hour_of_Day_1.0',
 'Hour_of_Day_2.0',
 'Hour_of_Day_3.0',
 'Hour_of_Day_4.0',
 'Hour_of_Day_5.0',
 'Hour_of_Day_6.0',
 'Hour_of_Day_7.0',
 'Hour_of_Day_8.0',
 'Hour_of_Day_9.0',
 'Hour_of_Day_10.0',
 'Hour_of_Day_11.0',
 'Hour_of_Day_12.0',
 'Hour_of_Day_13.0',
 'Hour_of_Day_14.0',
 'Hour_of_Day_15.0',
 'Hour_of_Day_16.0',
 'Hour_of_Day_17.0',
 'Hour_of_Day_18.0',
 'Hour_of_Day_19.0',
 'Hour_of_Day_20.0',
 'Hour_of_Day_21.0',
 'Hour_of_Day_22.0',
 'Hour_of_Day_23.0',
 'Illumination_Dark no street lights',
 'Illumination_Dark street lights',
 'Illumination_Dark unknown roadway lighting',
 'Illumination_Dawn',
 'Illumination_Daylight',
 'Illumination_Dusk',
 'Illumination_Other',
 'Weather_Fog',
 'Weather_No adverse conditions',
 'Weather_Other',
 'Weather_Rain',
 'Weather_Rain and fog',
 'Weather_Sleet and fog',
 'Weather_Sleet(hail)',
 'Weather_Snow',
 'Road_Condition_Dry',
 'Road_Condition_Ice',
 'Road_Condition_Ice Patches',
 'Road_Condition_Other',
 'Road_Condition_Sand/mud/dirt/oil/or gravel',
 'Road_Condition_Slush',
 'Road_Condition_Snow covered',
 'Road_Condition_Water - standing or moving',
 'Road_Condition_Wet',
 'Urban_/_Rural_Rural',
 'Urban_/_Rural_Urban',
 'Urban_/_Rural_Urbanized']

In [4]:
feature_list_boolean = [
 'Interstate',
 'State_Road',
 'Local_Road_Only',
 'Turnpike',
 'Non_Intersection',
 'Intersection',
 'Signalized_Intersection',
 'Stop_Controlled_Intersection',
 'Unsignalized_Intersection',
 'Alcohol_Related',
 'Drinking_Driver',
 'Underage_Drinking_Driver',
 'Unlicensed',
 'Distracted',
 'Cell_Phone',
 'No_Clearance',
 'Running_Red_Light',
 'Running_Stop_Sign',
 'Tailgating',
 'Cross_Median',
 'Curved_Road',
 'Curve_Driver_Error',
 'Limit_65_MPH',
 'Speeding',
 'Speeding_Related',
 'Aggressive_Driving',
 'Fatigue_/_Asleep',
 'Driver_16_Years_Old',
 'Driver_17_Years_Old',
 'Driver_18_Years_Old',
 'Driver_19_Years_Old',
 'Driver_20_Years_Old',
 'Driver_50_-_64_Years_Old',
 'Driver_65_-_74_Years_Old',
 'Driver_75_Plus',
 'NHTSA_Aggressive_Driving',
 'Weekend',
 'Crash_Month_1',
 'Crash_Month_2',
 'Crash_Month_3',
 'Crash_Month_4',
 'Crash_Month_5',
 'Crash_Month_6',
 'Crash_Month_7',
 'Crash_Month_8',
 'Crash_Month_9',
 'Crash_Month_10',
 'Crash_Month_11',
 'Crash_Month_12',
 'Hour_of_Day_0.0',
 'Hour_of_Day_1.0',
 'Hour_of_Day_2.0',
 'Hour_of_Day_3.0',
 'Hour_of_Day_4.0',
 'Hour_of_Day_5.0',
 'Hour_of_Day_6.0',
 'Hour_of_Day_7.0',
 'Hour_of_Day_8.0',
 'Hour_of_Day_9.0',
 'Hour_of_Day_10.0',
 'Hour_of_Day_11.0',
 'Hour_of_Day_12.0',
 'Hour_of_Day_13.0',
 'Hour_of_Day_14.0',
 'Hour_of_Day_15.0',
 'Hour_of_Day_16.0',
 'Hour_of_Day_17.0',
 'Hour_of_Day_18.0',
 'Hour_of_Day_19.0',
 'Hour_of_Day_20.0',
 'Hour_of_Day_21.0',
 'Hour_of_Day_22.0',
 'Hour_of_Day_23.0',
 'Illumination_Dark no street lights',
 'Illumination_Dark street lights',
 'Illumination_Dark unknown roadway lighting',
 'Illumination_Dawn',
 'Illumination_Daylight',
 'Illumination_Dusk',
 'Illumination_Other',
 'Weather_Fog',
 'Weather_No adverse conditions',
 'Weather_Other',
 'Weather_Rain',
 'Weather_Rain and fog',
 'Weather_Sleet and fog',
 'Weather_Sleet(hail)',
 'Weather_Snow',
 'Road_Condition_Dry',
 'Road_Condition_Ice',
 'Road_Condition_Ice Patches',
 'Road_Condition_Other',
 'Road_Condition_Sand/mud/dirt/oil/or gravel',
 'Road_Condition_Slush',
 'Road_Condition_Snow covered',
 'Road_Condition_Water - standing or moving',
 'Road_Condition_Wet',
 'Urban_/_Rural_Rural',
 'Urban_/_Rural_Urban',
 'Urban_/_Rural_Urbanized']

# machine learning

In [98]:
df.head()

Crash_Record_Number  Crash_Year  Day_of_Week         Collision_Type  \
0           2007000008        2007          2.0  Sideswipe (same dir.)   
1           2007000009        2007          2.0  Sideswipe (same dir.)   
2           2007000930        2007          6.0       Hit fixed object   
3           2007001994        2007          2.0       Hit fixed object   
4           2007004699        2007          6.0       Hit fixed object   

   Interstate  State_Road  Local_Road_Only  Turnpike  Non_Intersection  \
0         0.0         1.0              0.0       0.0               1.0   
1         0.0         1.0              0.0       0.0               1.0   
2         0.0         0.0              1.0       0.0               1.0   
3         1.0         1.0              0.0       0.0               1.0   
4         0.0         1.0              0.0       0.0               0.0   

   Intersection  Signalized_Intersection  Stop_Controlled_Intersection  \
0           0.0                      0.0                           0.0   
1           0.0                      0.0                           0.0   
2           0.0                      0.0                           0.0   
3           0.0                      0.0                           0.0   
4           1.0                      0.0                           0.0   

   Unsignalized_Intersection  Alcohol_Related  Drinking_Driver  \
0                        0.0              0.0              0.0   
1                        0.0              0.0              0.0   
2                        0.0              0.0              0.0   
3                        0.0              0.0              0.0   
4                        1.0              0.0              0.0   

   Underage_Drinking_Driver  Unlicensed  Distracted  Cell_Phone  No_Clearance  \
0                       0.0         0.0         0.0         0.0           0.0   
1                       0.0         0.0         0.0         0.0           0.0   
2                       0.0         0.0         0.0         0.0           0.0   
3                       0.0         0.0         0.0         0.0           0.0   
4                       0.0         0.0         0.0         0.0           0.0   

   Running_Red_Light  Running_Stop_Sign  Tailgating  Cross_Median  \
0                0.0                0.0         0.0           0.0   
1                0.0                0.0         0.0           0.0   
2                0.0                0.0         0.0           0.0   
3                0.0                0.0         0.0           0.0   
4                0.0                0.0         0.0           0.0   

   Curved_Road  Curve_Driver_Error  Limit_65_MPH  Speeding  Speeding_Related  \
0          0.0                 0.0           0.0       0.0               0.0   
1          0.0                 0.0           0.0       0.0               0.0   
2          0.0                 0.0           0.0       0.0               1.0   
3          0.0                 0.0           0.0       0.0               0.0   
4          0.0                 0.0           0.0       0.0               1.0   

   Aggressive_Driving  Fatigue_/_Asleep  Driver_16_Years_Old  \
0                 0.0               0.0                  0.0   
1                 0.0               0.0                  0.0   
2                 1.0               0.0                  0.0   
3                 0.0               0.0                  0.0   
4                 1.0               0.0                  0.0   

   Driver_17_Years_Old  Driver_18_Years_Old  Driver_19_Years_Old  \
0                  0.0                  0.0                  0.0   
1                  0.0                  0.0                  0.0   
2                  0.0                  0.0                  0.0   
3                  0.0                  0.0                  0.0   
4                  0.0                  0.0                  0.0   

   Driver_20_Years_Old  Driver_50_-_64_Years_Old  Driver_65_-_74_Years_Old  \
0               

In [5]:
X = df[feature_list].values

y = df.Collision_Type_num.values

# naive bayes model

In [6]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [113]:
X = df[feature_list_boolean].values
y = df.Collision_Type_num.values

In [125]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

In [126]:
clf = BernoulliNB()
clf.fit(X_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [128]:
y_pred = clf.predict(X_test)

In [129]:
# print(metrics.f1_score(y_test, y_pred,average=None))
print(clf.score(X_test, y_test))
print(metrics.balanced_accuracy_score(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

0.5664866978198946
0.32578269685811484
              precision    recall  f1-score   support

           0       0.63      0.70      0.66    140906
           1       0.00      0.00      0.00       884
           2       0.19      0.03      0.06     19574
           3       0.66      0.68      0.67    171300
           4       0.23      0.35      0.28     17553
           5       0.21      0.03      0.06     19520
           6       0.37      0.67      0.47     17933
           7       0.57      0.57      0.57    117194
           8       0.28      0.08      0.12     10640
           9       0.16      0.15      0.16     21626

   micro avg       0.57      0.57      0.57    537130
   macro avg       0.33      0.33      0.30    537130
weighted avg       0.55      0.57      0.55    537130

[[ 98032      1    739  13394   6234    219   1412  16281    552   4042]
 [   220      0      2    135    182      2     30    201      1    111]
 [  7436      0    646   6049    887     54    359   215

### cross-validation

In [140]:
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score

In [135]:
scoring = ['balanced_accuracy','f1_weighted']
scores = cross_validate(clf, X, y, scoring=scoring, cv=5, return_train_score=False)

C:\Users\Qingyu\Anaconda3\envs\project2env\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [136]:
scores

{'fit_time': array([2.91793966, 2.91228628, 2.90239692, 2.96460748, 2.97624779]),
 'score_time': array([0.82586813, 0.83380198, 0.83626866, 0.82947421, 0.83676147]),
 'test_balanced_accuracy': array([0.31220712, 0.32284163, 0.30773293, 0.33437341, 0.33010337]),
 'test_f1_weighted': array([0.54273602, 0.54818091, 0.53321385, 0.56358965, 0.5436464 ])}

In [137]:
scores['test_f1_weighted'].mean()

0.5462733653700307

In [132]:
print(cross_val_score(clf, X, y, cv=10))

[0.55245109 0.57373069 0.56725943 0.56719663 0.55019548 0.54103708
 0.58801451 0.58773896 0.57658308 0.53286465]


In [139]:
cross_val_score(clf, X, y, cv=5).mean()

0.5628365648997165

# KNN Classifier

In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [12]:
df_sample = df.sample(frac=0.1, replace=True,random_state=0)

In [13]:
X = df_sample[feature_list].values
y = df_sample.Collision_Type_num.values

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

In [15]:
times1 = datetime.now()
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
times2 = datetime.now()
print('Time spent: '+ str(times2-times1)) # print the time cost

Time spent: 0:06:00.932975


In [16]:
# print(metrics.f1_score(y_test, y_pred,average=None))
print(clf.score(X_test, y_test))
print(metrics.balanced_accuracy_score(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

0.5490849515014987
0.2662168703368101
              precision    recall  f1-score   support

           0       0.57      0.74      0.64     14037
           1       0.02      0.01      0.01        94
           2       0.11      0.03      0.05      2061
           3       0.60      0.72      0.66     17160
           4       0.26      0.19      0.22      1768
           5       0.11      0.04      0.06      1873
           6       0.41      0.41      0.41      1701
           7       0.55      0.45      0.50     11785
           8       0.07      0.01      0.01      1058
           9       0.16      0.05      0.08      2176

   micro avg       0.55      0.55      0.55     53713
   macro avg       0.29      0.27      0.26     53713
weighted avg       0.50      0.55      0.52     53713

[[10440     9   122  1674   285    68    62  1250    20   107]
 [   28     1     2    27     3     2     2    21     1     7]
 [  896     1    60   695    56    27    38   245     6    37]
 [ 1819    13 

# SVC

In [13]:
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [19]:
df_sample = df[df['Crash_Year'] == 2017]
# df_sample = df_sample.sample(frac=0.2, replace=True,random_state=0)

In [21]:
X = df_sample[feature_list].values
y = df_sample.Collision_Type_num.values

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [17]:
times1 = datetime.now()
clf = svm.SVC(kernel='linear', gamma='auto')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
times2 = datetime.now()
print('Time spent: '+ str(times2-times1)) # print the time cost

Time spent: 0:00:51.933609


In [22]:
y_pred = clf.predict(X)

In [18]:
# print(metrics.f1_score(y_test, y_pred,average=None))
print(clf.score(X_test, y_test))
print(metrics.balanced_accuracy_score(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

0.6295468400731559
0.2938003399791967
              precision    recall  f1-score   support

           0       0.67      0.80      0.73      1383
           1       0.00      0.00      0.00        15
           2       0.32      0.10      0.16       181
           3       0.62      0.79      0.70      1465
           4       0.55      0.10      0.17       156
           5       0.00      0.00      0.00       152
           6       0.61      0.48      0.54       181
           7       0.62      0.66      0.64      1075
           8       0.00      0.00      0.00        71
           9       0.33      0.00      0.01       242

   micro avg       0.63      0.63      0.63      4921
   macro avg       0.37      0.29      0.29      4921
weighted avg       0.57      0.63      0.58      4921

[[1111    0   11  130    3    0    7  121    0    0]
 [   2    0    0    7    1    0    0    5    0    0]
 [  96    0   19   40    0    0    0   25    1    0]
 [  92    0   14 1159    3    0   27  163   

C:\Users\Qingyu\Anaconda3\envs\project2env\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Qingyu\Anaconda3\envs\project2env\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Qingyu\Anaconda3\envs\project2env\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### cross-validation

In [31]:
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score

In [135]:
scoring = ['balanced_accuracy','f1_weighted']
scores = cross_validate(clf, X, y, scoring=scoring, cv=5, return_train_score=False)

C:\Users\Qingyu\Anaconda3\envs\project2env\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [136]:
scores

{'fit_time': array([2.91793966, 2.91228628, 2.90239692, 2.96460748, 2.97624779]),
 'score_time': array([0.82586813, 0.83380198, 0.83626866, 0.82947421, 0.83676147]),
 'test_balanced_accuracy': array([0.31220712, 0.32284163, 0.30773293, 0.33437341, 0.33010337]),
 'test_f1_weighted': array([0.54273602, 0.54818091, 0.53321385, 0.56358965, 0.5436464 ])}

In [137]:
scores['test_f1_weighted'].mean()

0.5462733653700307

In [32]:
print(cross_val_score(clf, X, y, cv=10))

[0.64705882 0.63108766 0.63337393 0.6196668  0.6195122  0.63495935
 0.64634146 0.63262815 0.63925081 0.62118126]


In [37]:
np.array([0.64705882, 0.63108766, 0.63337393, 0.6196668, 0.6195122, 0.63495935,
 0.64634146, 0.63262815, 0.63925081, 0.62118126]).mean()

0.632506044

In [38]:
df_sample = df[df['Crash_Year'] == 2017]

In [39]:
X = df_sample[feature_list].values
y = df_sample.Collision_Type_num.values

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# apply model to all 2017 data

In [41]:
y_pred = clf.predict(X)

In [42]:
print(metrics.classification_report(y, y_pred))
print(metrics.confusion_matrix(y, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.81      0.73     33672
           1       0.00      0.00      0.00       380
           2       0.33      0.15      0.21      4558
           3       0.60      0.78      0.68     35971
           4       0.49      0.08      0.14      3829
           5       0.00      0.00      0.00      4035
           6       0.58      0.45      0.51      4684
           7       0.64      0.68      0.66     27808
           8       0.28      0.02      0.03      2309
           9       0.32      0.00      0.01      5766

   micro avg       0.63      0.63      0.63    123012
   macro avg       0.39      0.30      0.30    123012
weighted avg       0.58      0.63      0.58    123012

[[27195     0   401  2981    87     0    87  2885    27     9]
 [   59     0     4   173     5     0     9   130     0     0]
 [ 1916     0   691  1273    13     0    20   598    46     1]
 [ 2655     0   395 28100    59     1   841  3865   

C:\Users\Qingyu\Anaconda3\envs\project2env\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Qingyu\Anaconda3\envs\project2env\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Qingyu\Anaconda3\envs\project2env\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Random Forest

In [24]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [15]:
# df_sample = df.sample(frac=0.1, replace=True,random_state=0)

In [25]:
df_sample = df

In [9]:
df_sample = df[df['Crash_Year'].isin([2014,2015,2016,2017])]

In [26]:
X = df_sample[feature_list].values
y = df_sample.Collision_Type_num.values

In [11]:
df_sample = df[df['Crash_Year'].isin([2013])]
X_2013 = df_sample[feature_list].values
y_2013 = df_sample.Collision_Type_num.values

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## best parameters
RandomForestClassifier(bootstrap=False,
            max_depth=40,
            max_features='auto',
            min_samples_leaf=1,
            min_samples_split=10,
            n_estimators=600,
            random_state=0)

## train on 2017 test on 2016

In [11]:
times1 = datetime.now()
clf = RandomForestClassifier(n_estimators=200, random_state=0)
# clf = RandomForestClassifier(bootstrap=False, # default True
#                              max_depth=40, # default None
#                              max_features='auto', # default auto
#                              min_samples_leaf=1, # default 1
#                              min_samples_split=10, # default 2
#                              n_estimators=600, # default 10
#                              random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
times2 = datetime.now()
print('Time spent: '+ str(times2-times1)) # print the time cost

Time spent: 0:14:23.409327


In [28]:
times1 = datetime.now()
clf = RandomForestClassifier(n_estimators=200, random_state=0)
# clf = RandomForestClassifier(bootstrap=False, # default True
#                              max_depth=None, # default None
#                              max_features='auto', # default auto
#                              min_samples_leaf=10, # default 1
#                              min_samples_split=20, # default 2
#                              n_estimators=100, # default 10
#                              random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
times2 = datetime.now()
print('Time spent: '+ str(times2-times1)) # print the time cost

Time spent: 0:12:19.287244


In [ ]:
clf.feature_importances_

In [12]:
# default model
# print(metrics.f1_score(y_test, y_pred,average=None))
print(clf.score(X_test, y_test))
print(metrics.balanced_accuracy_score(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

0.6437063653119357
0.32082662179171817
              precision    recall  f1-score   support

           0       0.70      0.78      0.73     70608
           1       0.03      0.00      0.00       429
           2       0.33      0.08      0.12      9804
           3       0.64      0.82      0.72     85517
           4       0.40      0.25      0.30      8759
           5       0.18      0.02      0.03      9808
           6       0.60      0.47      0.53      9100
           7       0.66      0.67      0.66     58267
           8       0.23      0.03      0.06      5334
           9       0.28      0.09      0.14     10939

   micro avg       0.64      0.64      0.64    268565
   macro avg       0.40      0.32      0.33    268565
weighted avg       0.60      0.64      0.61    268565

[[54801     4   460  7473  1139    80   184  5687   148   632]
 [  114     1     1   142    33     6     3   108     3    18]
 [ 4131     0   741  3333   117    15    52  1117   197   101]
 [ 3935     3

In [14]:
# n_estimators=200, random_state=0

# print(metrics.f1_score(y_test, y_pred,average=None))
print(clf.score(X_test, y_test))
print(metrics.balanced_accuracy_score(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

0.6675354656141788
0.363222808785333
              precision    recall  f1-score   support

           0       0.72      0.80      0.76      7088
           1       0.64      0.12      0.21        56
           2       0.61      0.13      0.21      1024
           3       0.64      0.85      0.73      8499
           4       0.49      0.25      0.33       926
           5       0.62      0.07      0.13       947
           6       0.66      0.49      0.56       890
           7       0.67      0.68      0.67      5832
           8       0.60      0.10      0.18       513
           9       0.43      0.13      0.20      1082

   micro avg       0.67      0.67      0.67     26857
   macro avg       0.61      0.36      0.40     26857
weighted avg       0.65      0.67      0.63     26857

[[5702    1   16  743   73    5   12  498    7   31]
 [  12    7    0   22    3    0    0   11    0    1]
 [ 393    0  132  336   12    1    6  114   18   12]
 [ 352    2   22 7202   42   17  109  702    

# RandomizedSearchCV

In [17]:
clf = RandomForestClassifier(n_estimators=100, random_state=0)

In [18]:
nfolds = 3
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 1000, num = 5)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]

In [19]:
params_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

In [20]:
from sklearn.model_selection import RandomizedSearchCV

In [21]:
randomized = RandomizedSearchCV(clf, param_distributions=params_grid, n_iter = 20, cv=nfolds, scoring='balanced_accuracy',verbose=10,n_jobs=-1)

In [22]:
times1 = datetime.now()
randomized.fit(X, y)
times2 = datetime.now()
print('Time spent: '+ str(times2-times1)) # print the time cost

Fitting 3 folds for each of 20 candidates, totalling 60 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 6 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:   45.0s
[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:  2.3min
[Parallel(n_jobs=-1)]: Done  13 tasks      | elapsed:  3.8min
[Parallel(n_jobs=-1)]: Done  20 tasks      | elapsed:  5.3min
[Parallel(n_jobs=-1)]: Done  29 tasks      | elapsed:  9.1min
[Parallel(n_jobs=-1)]: Done  38 tasks      | elapsed: 12.6min
[Parallel(n_jobs=-1)]: Done  49 tasks      | elapsed: 15.8min
[Parallel(n_jobs=-1)]: Done  56 out of  60 | elapsed: 17.2min remaining:  1.2min
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed: 17.6min finished


Time spent: 0:19:24.399566


In [23]:
randomized.best_estimator_

RandomForestClassifier(bootstrap=False, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=600, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [25]:
randomized.best_score_

0.32171657664166065